version: "3.9"

networks: 
 jmeter-net:
  driver: bridge
  ipam:
    config:
      - subnet: ${JMETER_SUBNET}
volumes:
  jmeter-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
     # device: '/opt/jmeter-vol'


services:
  slave1:
    image: hmutyala/jmeter-distslave
    container_name: jmeter-slave1
    restart: "no"
    networks:
      jmeter-net:
        ipv4_address: ${JMETERIP_SLAVE1}
    volumes:
      - jmeter-vol:/mnt/jmeter
    command:
      - -n -Jclient.rmi.localport=${JMETER_CLIENTPORT} -Jserver.rmi.localport={JMETER_SERVERPORT}
      - -j /mnt/jmeter/slave_${JMETERIP_SLAVE1}.logdone

  slave2:
    image: hmutyala/jmeter-distslave
    container_name: jmeter-slave2
    restart: "no"
    networks:
      jmeter-net:
        ipv4_address: ${JMETERIP_SLAVE2}
    volumes:
     - jmeter-vol:/mnt/jmeter
    command:
      - -n -Jclient.rmi.localport=${JMETER_CLIENTPORT} -Jserver.rmi.localport={JMETER_SERVERPORT}
      - -j /mnt/jmeter/slave_${JMETERIP_SLAVE2}.logdone
  
  slave3:
    image: hmutyala/jmeter-distslave
    container_name: jmeter-slave3
    restart: "no"
    networks:
      jmeter-net:
        ipv4_address: ${JMETERIP_SLAVE3}
    volumes:
      - jmeter-vol:/mnt/jmeter
    command:
      - -n -Jclient.rmi.localport=${JMETER_CLIENTPORT} -Jserver.rmi.localport={JMETER_SERVERPORT}
      - -j /mnt/jmeter/slave_${JMETERIP_SLAVE3}.logdone
 
  master:
    image: hmutyala/jmeter-distmaster
    container_name: jmeter-master
    networks:
      jmeter-net:
        ipv4_address: ${JMETERIP_MASTER}
    volumes:
      - jmeter-vol:/mnt/jmeter
    command:      
      -Jclient.rmi.localport=7000 -R ${JMETERIP_SLAVE1},${JMETERIP_SLAVE2},${JMETERIP_SLAVE3}    
    depends_on:
      - slave1
      - slave2
      - slave3
